# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contactinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='City',
            field=models.CharField(max_length=100, verbose_name='City:'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='StreetAddress',
            field=models.CharField(max_length=100, verbose_name='Street Address:'),
        ),
    ]
