# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170705_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='Gender',
            field=models.CharField(default='Male/Female', max_length=6, verbose_name='Gender Male/Female:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='DoB',
            field=models.DateField(max_length=8, verbose_name='Date of Birth mm/dd/yy:'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='State',
            field=models.CharField(max_length=2, verbose_name='State Abbreviation:'),
        ),
    ]
